name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  # --- Static analysis (Rails/Ruby) ---
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - run: bin/brakeman --no-pager

  # --- JS dependency audit (Importmap) ---
  scan_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - run: bin/importmap audit

  # --- RuboCop only (テストは走らせない) ---
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - run: bin/rubocop -f github

  # --- RSpec ---
  rspec:
    runs-on: ubuntu-latest

    # ← サービスコンテナの pull より前に渡す必要があるため job レベルに置く
    env:
      DOCKER_AUTH_CONFIG: >-
        {"auths":{"https://index.docker.io/v1/":{"auth":"${{ secrets.DOCKERHUB_AUTH_B64 }}"}}}
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      DB_NAME: app_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      JUDGE0_BASE_URL: https://judge0-ce.p.rapidapi.com
      JUDGE0_RAPIDAPI_KEY: ${{ secrets.JUDGE0_RAPIDAPI_KEY }}
      JUDGE0_HOST_HEADER: judge0-ce.p.rapidapi.com

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        ports: [ '5432:5432' ]
        options: >-
          --health-cmd="pg_isready -U postgres -h localhost"
          --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            build-essential git pkg-config libpq-dev libyaml-dev \
            libvips libvips-dev
          ldconfig -p | grep libvips || true

      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npm run build:css
      - run: bin/rails db:prepare
      - run: bundle exec rspec
